export const generateHeatSinkJSX = (cooldown: number, range: number, resistDamageTaken: boolean) => {
  return (
    <>
      <b><i style={{ color: '#b17fbe' }}>Heat Sink</i></b> <span style={{ color: '#b17fbe', fontSize: '1em' }}><i>(Cooldown <b style={{ color: '#000', fontStyle: 'normal' }}>[{cooldown}]</b>).</i></span> Until the start of the next round, each time an ally within <b>[{range}]</b>hx of you would take <b><u style={{ color: '#de7204', display: 'inline-flex', alignItems: 'center' }}>Chemical<img src="/Chemical.png" alt="Chemical" style={{ width: 14, height: 14, marginLeft: 2, verticalAlign: 'middle' }} /></u></b>, <b><u style={{ color: '#3ebbff', display: 'inline-flex', alignItems: 'center' }}>Cold<img src="/Cold.png" alt="Cold" style={{ width: 14, height: 14, marginLeft: 2, verticalAlign: 'middle' }} /></u></b>, <b><u style={{ color: '#d5d52a', display: 'inline-flex', alignItems: 'center' }}>Electric<img src="/Electric.png" alt="Electric" style={{ width: 14, height: 14, marginLeft: 2, verticalAlign: 'middle' }} /></u></b>, <b><u style={{ color: '#f90102', display: 'inline-flex', alignItems: 'center' }}>Fire<img src="/Fire.png" alt="Fire" style={{ width: 14, height: 14, marginLeft: 2, verticalAlign: 'middle' }} /></u></b>, <b><u style={{ color: '#516fff', display: 'inline-flex', alignItems: 'center' }}>Force<img src="/Force.png" alt="Force" style={{ width: 14, height: 14, marginLeft: 2, verticalAlign: 'middle' }} /></u></b>, <b><u style={{ color: '#a929ff', display: 'inline-flex', alignItems: 'center' }}>Neural<img src="/Neural.png" alt="Neural" style={{ width: 14, height: 14, marginLeft: 2, verticalAlign: 'middle' }} /></u></b> or <b><u style={{ color: '#41f434', display: 'inline-flex', alignItems: 'center' }}>Toxic<img src="/Toxic.png" alt="Toxic" style={{ width: 14, height: 14, marginLeft: 2, verticalAlign: 'middle' }} /></u></b> Damage, you take that Damage instead which you <b>[</b>{resistDamageTaken ? <><i>Resist</i></> : ' - '}<b>]</b>. Additionally, you gain +1d6 <b><u style={{ color: '#f90102', display: 'inline-flex', alignItems: 'center' }}>Fire<img src="/Fire.png" alt="Fire" style={{ width: 14, height: 14, marginLeft: 2, verticalAlign: 'middle' }} /></u></b> on your next <b><i style={{ color: '#351c75' }}>Strike</i></b> or <b><i style={{ color: '#990000' }}>Attack</i></b> for each time you take Damage this round.
    </>
  );
};

export const generateHeatSinkCardJSX = (range: number, resistDamageTaken: boolean) => {
  return (
    <>
      Until the start of the next round, each time an ally within <b>[{range}]</b>hx of you would take <b><u style={{ color: '#de7204', display: 'inline-flex', alignItems: 'center' }}>Chemical<img src="/Chemical.png" alt="Chemical" style={{ width: 11.76, height: 11.76, marginLeft: 2, verticalAlign: 'middle' }} /></u></b>, <b><u style={{ color: '#3ebbff', display: 'inline-flex', alignItems: 'center' }}>Cold<img src="/Cold.png" alt="Cold" style={{ width: 11.76, height: 11.76, marginLeft: 2, verticalAlign: 'middle' }} /></u></b>, <b><u style={{ color: '#d5d52a', display: 'inline-flex', alignItems: 'center' }}>Electric<img src="/Electric.png" alt="Electric" style={{ width: 11.76, height: 11.76, marginLeft: 2, verticalAlign: 'middle' }} /></u></b>, <b><u style={{ color: '#f90102', display: 'inline-flex', alignItems: 'center' }}>Fire<img src="/Fire.png" alt="Fire" style={{ width: 11.76, height: 11.76, marginLeft: 2, verticalAlign: 'middle' }} /></u></b>, <b><u style={{ color: '#516fff', display: 'inline-flex', alignItems: 'center' }}>Force<img src="/Force.png" alt="Force" style={{ width: 11.76, height: 11.76, marginLeft: 2, verticalAlign: 'middle' }} /></u></b>, <b><u style={{ color: '#a929ff', display: 'inline-flex', alignItems: 'center' }}>Neural<img src="/Neural.png" alt="Neural" style={{ width: 11.76, height: 11.76, marginLeft: 2, verticalAlign: 'middle' }} /></u></b> or <b><u style={{ color: '#41f434', display: 'inline-flex', alignItems: 'center' }}>Toxic<img src="/Toxic.png" alt="Toxic" style={{ width: 11.76, height: 11.76, marginLeft: 2, verticalAlign: 'middle' }} /></u></b> Damage, you take that Damage instead which you <b>[</b>{resistDamageTaken ? <><i>Resist</i></> : ' - '}<b>]</b>. Additionally, you gain +1d6 <b><u style={{ color: '#f90102', display: 'inline-flex', alignItems: 'center' }}>Fire<img src="/Fire.png" alt="Fire" style={{ width: 11.76, height: 11.76, marginLeft: 2, verticalAlign: 'middle' }} /></u></b> on your next <b><i style={{ color: '#351c75' }}>Strike</i></b> or <b><i style={{ color: '#990000' }}>Attack</i></b> for each time you take Damage this round.
    </>
  );
};
